name: version_checker
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-174.3.beta

dependencies:
  args: ^2.4.2
  pubspec_parse: ^1.2.3
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
